---
# common settings
# local account to connect VIA winrm. (first to create the PDC)
ansible_user: administrator
ansible_password: Password1 #Password1,

ansible_port: 5985
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore

# rolesettings create_ad_structure
# ad-settings
domain: "euc-lab.de"
netbios_domain: "euc-lab"
domain_admin: "administrator@{{ domain }}"
domain_admin_password: Password1

city_ou: Muenster # City OU under the root OU Citrix
domainuser_password: Password1