---
# first reboot, if the Server ist in reboot state
# - name: Check if reboot is required
#   win_command: powershell.exe "Get-Item 'HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired'"
#   register: reboot
#   ignore_errors: yes
#   tags: reboot_check
      
# - name: Check to see if Reboot
#   debug: 
#     msg: Reboot is required
#   when: reboot.stdout.find("RebootRequired") != -1
#   tags: reboot_check

# ensure the named domain is reachable from the target host; if not, create the domain in a new forest residing on the target host
- name: install ad
  win_domain:
    dns_domain_name: "{{ domain }}"
    domain_netbios_name: "{{ netbios_domain }}"
    safe_mode_password: "{{ domain_safemode_password }}"
  register: ad

# Creating a Domain Controller requires a reboot
- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 240
  when: ad.changed

- name: Ensure the server is a domain controller
  win_domain_controller:
    dns_domain_name: "{{ domain }}"
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: "{{ domain_admin_password }}"
    safe_mode_password: "{{ domain_safemode_password }}"
    state: domain_controller
    #log_path: c:\ansible_win_domain_controller.txt
  register: check_domain_controller

# Creating a Domain Controller requires a reboot
# Long delay post boot since the DC configuration takes a while
- name: Reboot to complete domain controller setup
  win_reboot:
    shutdown_timeout: 600
    reboot_timeout: 600
    post_boot_delay: 240
  when: check_domain_controller.changed

# set dns forwarders 
- name: set dns forwarders
  ansible.windows.win_powershell:
    script: |
      Add-DnsServerForwarder -IPAddress 8.8.8.8 -PassThru